CREATE TABLE IF NOT EXISTS movies (id INT PRIMARY KEY, title VARCHAR(255), genre VARCHAR(50), year INT, runtime INT, language VARCHAR(50), rating DECIMAL(3,1));
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (1, 'The Shawshank Redemption', 'Drama', 2024, 176, 'German', 4.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (2, 'The Godfather', 'Romance', 1994, 98, 'German', 2.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (3, 'The Dark Knight', 'Comedy', 2019, 142, 'Italian', 1.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (4, 'Pulp Fiction', 'Romance', 2009, 119, 'Mandarin', 8.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (5, 'Forrest Gump', 'Fantasy', 1988, 100, 'Portuguese', 3.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (6, 'Inception', 'Comedy', 2016, 91, 'Japanese', 2.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (7, 'Fight Club', 'Horror', 2007, 160, 'Italian', 6.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (8, 'The Matrix', 'Documentary', 2024, 151, 'Japanese', 1.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (9, 'The Lord of the Rings', 'Drama', 2021, 82, 'Korean', 2.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (10, 'Star Wars: A New Hope', 'Action', 2010, 173, 'Korean', 9.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (11, 'The Avengers', 'Thriller', 2004, 144, 'German', 2.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (12, 'Gladiator', 'Thriller', 2021, 142, 'Italian', 2.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (13, 'Interstellar', 'Romance', 2015, 161, 'English', 6.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (14, 'Saving Private Ryan', 'Drama', 2007, 96, 'Portuguese', 7.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (15, 'Titanic', 'Sci-Fi', 2016, 168, 'Italian', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (16, 'Schindler List', 'Drama', 1988, 166, 'Hindi', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (17, 'Jurassic Park', 'Romance', 1990, 81, 'Japanese', 3.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (18, 'Braveheart', 'Fantasy', 2018, 114, 'Portuguese', 2.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (19, 'The Lion King', 'Documentary', 2003, 135, 'Italian', 9.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (20, 'Avatar', 'Fantasy', 2000, 145, 'French', 4.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (21, 'The Silence of the Lambs', 'Thriller', 2015, 127, 'English', 3.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (22, 'Goodfellas', 'Documentary', 1988, 100, 'English', 3.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (23, 'The Departed', 'Drama', 2022, 160, 'French', 6.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (24, 'The Prestige', 'Action', 2001, 172, 'Mandarin', 4.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (25, 'The Terminator', 'Animation', 1998, 166, 'Italian', 1.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (26, 'Alien', 'Horror', 2017, 98, 'German', 3.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (27, 'Die Hard', 'Fantasy', 2003, 93, 'Japanese', 1.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (28, 'Mad Max: Fury Road', 'Documentary', 1986, 80, 'French', 8.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (29, 'The Social Network', 'Drama', 1995, 131, 'Portuguese', 6.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (30, 'Black Panther', 'Animation', 1991, 118, 'Korean', 5.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (31, 'Joker', 'Romance', 2022, 100, 'English', 3.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (32, 'Parasite', 'Documentary', 2017, 81, 'Korean', 7.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (33, 'Whiplash', 'Fantasy', 2004, 142, 'Italian', 1.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (34, '12 Years a Slave', 'Thriller', 2016, 84, 'German', 4.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (35, 'La La Land', 'Action', 1994, 91, 'German', 3.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (36, 'Django Unchained', 'Animation', 1989, 128, 'Mandarin', 6.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (37, 'Shutter Island', 'Action', 2018, 129, 'Japanese', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (38, 'A Beautiful Mind', 'Thriller', 2020, 124, 'Hindi', 5.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (39, 'The Green Mile', 'Thriller', 2007, 171, 'Mandarin', 6.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (40, 'The Wolf of Wall Street', 'Horror', 1981, 89, 'Spanish', 8.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (41, 'The Revenant', 'Documentary', 1984, 120, 'Mandarin', 7.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (42, 'The Big Short', 'Drama', 1988, 86, 'Portuguese', 3.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (43, 'Blade Runner 2049', 'Documentary', 2024, 82, 'German', 6.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (44, 'Bohemian Rhapsody', 'Horror', 2022, 176, 'Spanish', 9.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (45, 'Spider-Man: Into the Spider-Verse', 'Fantasy', 1999, 114, 'Spanish', 9.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (46, 'Avengers: Endgame', 'Documentary', 2000, 90, 'Korean', 4.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (47, 'Guardians of the Galaxy', 'Animation', 2009, 121, 'Portuguese', 8.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (48, 'The Grand Budapest Hotel', 'Sci-Fi', 1990, 125, 'Japanese', 7.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (49, 'The Imitation Game', 'Romance', 1987, 172, 'Portuguese', 1.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (50, 'Doctor Strange', 'Thriller', 2016, 147, 'Portuguese', 2.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (51, 'The Hateful Eight', 'Fantasy', 1985, 139, 'English', 5.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (52, 'Once Upon a Time in Hollywood', 'Thriller', 1997, 137, 'Spanish', 4.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (53, 'Toy Story', 'Horror', 1988, 91, 'Spanish', 2.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (54, 'Frozen', 'Documentary', 2017, 121, 'German', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (55, 'Finding Nemo', 'Sci-Fi', 2012, 101, 'German', 9.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (56, 'The Incredibles', 'Fantasy', 2000, 114, 'Italian', 9.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (57, 'Up', 'Action', 2016, 178, 'German', 8.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (58, 'Coco', 'Fantasy', 1993, 95, 'Portuguese', 6.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (59, 'WALL-E', 'Sci-Fi', 1983, 146, 'German', 9.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (60, 'Monsters, Inc.', 'Animation', 2024, 107, 'Spanish', 9.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (61, 'Inside Out', 'Sci-Fi', 2004, 176, 'English', 9.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (62, 'Ratatouille', 'Thriller', 1984, 135, 'Portuguese', 7.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (63, 'Zootopia', 'Horror', 1981, 161, 'Portuguese', 6.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (64, 'Moana', 'Thriller', 2019, 87, 'English', 2.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (65, 'Beauty and the Beast', 'Drama', 1998, 116, 'Italian', 1.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (66, 'Aladdin', 'Drama', 1984, 95, 'Japanese', 3.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (67, 'Snow White and the Seven Dwarfs', 'Documentary', 2021, 149, 'Japanese', 3.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (68, 'The Little Mermaid', 'Action', 1994, 108, 'German', 4.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (69, 'Cinderella', 'Animation', 2014, 128, 'Italian', 7.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (70, 'Sleeping Beauty', 'Drama', 1991, 94, 'English', 9.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (71, 'Mulan', 'Sci-Fi', 1993, 102, 'French', 6.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (72, 'Pocahontas', 'Sci-Fi', 1995, 81, 'Hindi', 6.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (73, 'Tangled', 'Documentary', 1985, 128, 'Korean', 1.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (74, 'Brave', 'Documentary', 2014, 104, 'German', 8.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (75, 'Frozen II', 'Animation', 2005, 110, 'Japanese', 3.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (76, 'The Jungle Book', 'Documentary', 2011, 155, 'Hindi', 1.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (77, 'Mary Poppins', 'Romance', 2017, 178, 'German', 9.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (78, 'Pinocchio', 'Fantasy', 2013, 143, 'Japanese', 9.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (79, 'Peter Pan', 'Animation', 2007, 150, 'English', 3.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (80, 'Alice in Wonderland', 'Comedy', 2007, 85, 'Mandarin', 3.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (81, 'Bambi', 'Comedy', 1999, 118, 'English', 8.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (82, 'Dumbo', 'Drama', 2022, 119, 'Mandarin', 5.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (83, 'Fantasia', 'Action', 2009, 145, 'Italian', 8.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (84, '101 Dalmatians', 'Action', 1988, 146, 'Japanese', 1.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (85, 'Lady and the Tramp', 'Fantasy', 2009, 108, 'German', 9.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (86, 'The Sword in the Stone', 'Fantasy', 1984, 149, 'Korean', 6.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (87, 'Robin Hood', 'Drama', 1998, 110, 'Hindi', 6.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (88, 'The Aristocats', 'Comedy', 1993, 122, 'Hindi', 7.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (89, 'The Rescuers', 'Drama', 2017, 91, 'English', 8.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (90, 'Hercules', 'Comedy', 1997, 95, 'French', 2.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (91, 'Tarzan', 'Sci-Fi', 2003, 167, 'German', 1.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (92, 'Lilo & Stitch', 'Horror', 2014, 119, 'Japanese', 1.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (93, 'The Princess and the Frog', 'Thriller', 2019, 146, 'Portuguese', 6.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (94, 'Big Hero 6', 'Fantasy', 2009, 95, 'German', 5.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (95, 'Wreck-It Ralph', 'Sci-Fi', 2023, 148, 'Spanish', 8.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (96, 'Ralph Breaks the Internet', 'Thriller', 2006, 164, 'German', 3.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (97, 'Cars', 'Comedy', 2006, 80, 'French', 8.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (98, 'Cars 2', 'Fantasy', 2018, 139, 'Spanish', 1.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (99, 'Cars 3', 'Sci-Fi', 1982, 150, 'Mandarin', 2.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (100, 'Toy Story 2', 'Animation', 2022, 105, 'Hindi', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (101, 'Toy Story 3', 'Horror', 1984, 134, 'Italian', 8.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (102, 'Toy Story 4', 'Documentary', 1994, 92, 'English', 3.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (103, 'Monsters University', 'Animation', 1990, 98, 'Korean', 7.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (104, 'Incredibles 2', 'Romance', 2002, 85, 'Portuguese', 2.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (105, 'Despicable Me', 'Comedy', 1987, 118, 'Hindi', 1.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (106, 'Minions', 'Drama', 1998, 162, 'French', 1.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (107, 'The Secret Life of Pets', 'Drama', 1999, 102, 'German', 4.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (108, 'Sing', 'Documentary', 2002, 167, 'Japanese', 3.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (109, 'Shrek', 'Documentary', 1988, 127, 'French', 1.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (110, 'Shrek 2', 'Comedy', 1981, 106, 'Italian', 9.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (111, 'Shrek the Third', 'Thriller', 2001, 177, 'French', 1.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (112, 'Shrek Forever After', 'Fantasy', 2017, 119, 'French', 4.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (113, 'Madagascar', 'Romance', 1987, 164, 'Italian', 3.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (114, 'Kung Fu Panda', 'Sci-Fi', 2009, 103, 'Japanese', 5.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (115, 'How to Train Your Dragon', 'Fantasy', 2021, 135, 'Japanese', 6.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (116, 'The Croods', 'Action', 2009, 97, 'French', 7.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (117, 'Trolls', 'Sci-Fi', 2022, 117, 'Italian', 5.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (118, 'Megamind', 'Sci-Fi', 2000, 170, 'French', 9.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (119, 'The Boss Baby', 'Animation', 1992, 102, 'Portuguese', 7.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (120, 'Rise of the Guardians', 'Sci-Fi', 1999, 129, 'Korean', 1.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (121, 'The Peanuts Movie', 'Documentary', 1987, 177, 'Italian', 2.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (122, 'Ice Age', 'Sci-Fi', 1988, 131, 'Korean', 2.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (123, 'Ice Age: The Meltdown', 'Drama', 2008, 125, 'Japanese', 9.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (124, 'Ice Age: Dawn of the Dinosaurs', 'Horror', 1990, 98, 'Japanese', 4.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (125, 'Ice Age: Continental Drift', 'Documentary', 2014, 168, 'French', 2.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (126, 'Ice Age: Collision Course', 'Animation', 1994, 124, 'English', 3.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (127, 'The Shawshank Redemption', 'Drama', 1994, 113, 'German', 8.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (128, 'The Godfather', 'Sci-Fi', 1999, 104, 'Spanish', 3.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (129, 'The Dark Knight', 'Fantasy', 2020, 165, 'Hindi', 3.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (130, 'Pulp Fiction', 'Action', 1995, 122, 'Portuguese', 10.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (131, 'Forrest Gump', 'Comedy', 1981, 84, 'Japanese', 2.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (132, 'Inception', 'Animation', 2010, 155, 'English', 6.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (133, 'Fight Club', 'Sci-Fi', 2002, 82, 'Hindi', 8.4);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (134, 'The Matrix', 'Horror', 1988, 115, 'German', 2.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (135, 'The Lord of the Rings', 'Comedy', 2002, 82, 'Hindi', 2.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (136, 'Star Wars: A New Hope', 'Drama', 1986, 151, 'Italian', 5.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (137, 'The Avengers', 'Action', 2024, 123, 'German', 6.1);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (138, 'Gladiator', 'Drama', 2008, 107, 'French', 5.9);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (139, 'Interstellar', 'Documentary', 1994, 140, 'English', 7.3);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (140, 'Saving Private Ryan', 'Thriller', 2022, 100, 'Hindi', 5.2);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (141, 'Titanic', 'Comedy', 2002, 107, 'Japanese', 2.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (142, 'Schindler List', 'Fantasy', 1989, 116, 'Korean', 5.8);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (143, 'Jurassic Park', 'Romance', 1994, 90, 'Japanese', 4.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (144, 'Braveheart', 'Animation', 1992, 106, 'Italian', 9.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (145, 'The Lion King', 'Horror', 1994, 103, 'Korean', 3.5);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (146, 'Avatar', 'Drama', 1998, 117, 'French', 2.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (147, 'The Silence of the Lambs', 'Horror', 2013, 146, 'Spanish', 2.7);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (148, 'Goodfellas', 'Action', 2009, 113, 'English', 2.0);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (149, 'The Departed', 'Drama', 1987, 137, 'Japanese', 2.6);
INSERT INTO movies (id, title, genre, year, runtime, language, rating) VALUES (150, 'The Prestige', 'Animation', 1986, 150, 'Korean', 6.6);


create database movies;

use movies;

show tables;



